_wandb:
    value:
        cli_version: 0.24.0
        e:
            s4oq0dv4sycr8v2wx7ru9kqnzvgpomvw:
                apple:
                    ecpuCores: 4
                    gpuCores: 30
                    memoryGb: 32
                    name: Apple M2 Max
                    pcpuCores: 8
                    ramTotalBytes: "34359738368"
                args:
                    - --input_artifact
                    - raw_data.parquet:latest
                    - --artifact_name
                    - preprocessed_data.csv
                    - --artifact_type
                    - preprocessed_data
                    - --artifact_description
                    - Data with preprocessing applied
                codePath: preprocess/run.py
                codePathLocal: run.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "994662584320"
                        used: "175622729728"
                email: yeabzed19@gmail.com
                executable: /Users/yeabsiraeshetu/miniconda3/envs/mlflow-0c0de061eeaefd8cf19694dcf7baac6a336c7f6b/bin/python
                git:
                    commit: dd9ba41524b14c6c9d06a22544f3595c61f4075b
                    remote: git@github.com:code-lit/genre_classification.git
                host: Yeabsiras-MacBook-Pro.local
                memory:
                    total: "34359738368"
                os: macOS-13.5-arm64-arm-64bit-Mach-O
                program: /Users/yeabsiraeshetu/Desktop/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/starter/genre_classification/preprocess/run.py
                python: CPython 3.13.12
                root: /Users/yeabsiraeshetu/Desktop/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/starter/genre_classification/preprocess
                startedAt: "2026-02-19T01:07:46.583404Z"
                writerId: s4oq0dv4sycr8v2wx7ru9kqnzvgpomvw
        m: []
        python_version: 3.13.12
        t:
            "4": 3.13.12
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
