_wandb:
    value:
        cli_version: 0.24.0
        e:
            hfmkmzyxkbmzhx830kq33vw7j1hgj38i:
                apple:
                    ecpuCores: 4
                    gpuCores: 30
                    memoryGb: 32
                    name: Apple M2 Max
                    pcpuCores: 8
                    ramTotalBytes: "34359738368"
                args:
                    - --train_data
                    - data_train.csv:latest
                    - --model_config
                    - /Users/yeabsiraeshetu/Desktop/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/starter/genre_classification/outputs/2026-02-18/17-06-44/random_forest_config.yml
                    - --export_artifact
                    - model_export
                    - --random_seed
                    - "42"
                    - --val_size
                    - "0.3"
                    - --stratify
                    - genre
                codePath: random_forest/run.py
                codePathLocal: run.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "994662584320"
                        used: "176860639232"
                email: yeabzed19@gmail.com
                executable: /Users/yeabsiraeshetu/miniconda3/envs/mlflow-484df64d71fdfb8fbb5f48803452d41c922ae5e3/bin/python
                git:
                    commit: dd9ba41524b14c6c9d06a22544f3595c61f4075b
                    remote: git@github.com:code-lit/genre_classification.git
                host: Yeabsiras-MacBook-Pro.local
                memory:
                    total: "34359738368"
                os: macOS-13.5-arm64-arm-64bit-Mach-O
                program: /Users/yeabsiraeshetu/Desktop/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/starter/genre_classification/random_forest/run.py
                python: CPython 3.13.12
                root: /Users/yeabsiraeshetu/Desktop/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/starter/genre_classification/random_forest
                startedAt: "2026-02-19T01:10:47.292293Z"
                writerId: hfmkmzyxkbmzhx830kq33vw7j1hgj38i
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 62
            "4": 3.13.12
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
export_artifact:
    value: model_export
features:
    value:
        categorical:
            - time_signature
            - key
        nlp:
            - text_feature
        numerical:
            - danceability
            - energy
            - loudness
            - speechiness
            - acousticness
            - instrumentalness
            - liveness
            - valence
            - tempo
            - duration_ms
random_forest:
    value:
        bootstrap: true
        ccp_alpha: 0
        class_weight: balanced
        criterion: gini
        max_depth: 13
        max_features: null
        max_leaf_nodes: null
        max_samples: null
        min_impurity_decrease: 0
        min_samples_leaf: 1
        min_samples_split: 2
        min_weight_fraction_leaf: 0
        n_estimators: 100
        n_jobs: null
        oob_score: false
        random_state: 42
        verbose: 0
        warm_start: false
tfidf:
    value:
        max_features: 10
