_wandb:
    value:
        cli_version: 0.24.0
        e:
            hsdj3r00udpgmtdhxm3bjb1bcduhvsfz:
                apple:
                    ecpuCores: 4
                    gpuCores: 30
                    memoryGb: 32
                    name: Apple M2 Max
                    pcpuCores: 8
                    ramTotalBytes: "34359738368"
                args:
                    - --file_url
                    - https://github.com/udacity/nd0821-c2-build-model-workflow-exercises/blob/master/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/genres_mod.parquet?raw=true
                    - --artifact_name
                    - raw_data.parquet
                    - --artifact_type
                    - raw_data
                    - --artifact_description
                    - Data as downloaded
                codePath: download/download_data.py
                codePathLocal: download_data.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "994662584320"
                        used: "175331954688"
                email: yeabzed19@gmail.com
                executable: /Users/yeabsiraeshetu/miniconda3/envs/mlflow-6020c6165ff66772b09c5cc54c9af39b0c9c44b4/bin/python
                git:
                    commit: dd9ba41524b14c6c9d06a22544f3595c61f4075b
                    remote: git@github.com:code-lit/genre_classification.git
                host: Yeabsiras-MacBook-Pro.local
                memory:
                    total: "34359738368"
                os: macOS-13.5-arm64-arm-64bit-Mach-O
                program: /Users/yeabsiraeshetu/Desktop/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/starter/genre_classification/download/download_data.py
                python: CPython 3.13.12
                root: /Users/yeabsiraeshetu/Desktop/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/starter/genre_classification/download
                startedAt: "2026-02-19T01:07:12.242670Z"
                writerId: hsdj3r00udpgmtdhxm3bjb1bcduhvsfz
        m: []
        python_version: 3.13.12
        t:
            "3":
                - 2
            "4": 3.13.12
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
